INN/largo

partials/author-bio-description.php
partials/author-bio-social-links.php

We noticed a bug in Chicago Reporter site wherein due to Co-authors Plus the bio widget wasn't properly displaying links to author archive pages. Per https://wordpress.org/support/topic/get_author_posts_url-not-working-for-guest-authors we've adjusted the calls to get_author_posts_url() to rectify the problem.

Fixing bug in author bio widget where URLs were missing

---

inc/taxonomies.php
options.php
phpunit.xml
tests/bootstrap.php
tests/inc/test-avatars.php
tests/inc/test-helpers.php
tests/inc/test-taxonomies.php
tests/inc/test-users.php
tests/mock/mock-admin-functions.php
tests/mock/test-mock-admin-functions.php

This depends on/extends #328, and cherrypicks the post-type-specific commits from #312. It is half of the solution to #282.
Unless the option box is checked in Theme Settings > Advanced:
- The "Post Types" menu item is removed from the sidebar in the dashboard
- The "Post Types" metabox is removed from the post editor
- The "Post Types" column is removed from the table of posts and details

Optional post types

---

inc/customizer/customizer.php
inc/enqueue.php
lib/options-framework/css/optionsframework.css
options.php
partials/content-single-classic.php
tests/inc/test-enqueue.php

This uses a different slug, `single_social_icons`, so it shouldn't conflict with the old `social_icons_display` drop-down option.

Single post social icon checkbox for #326

---

css/style.css
less/inc/navbar.less

This is a small follow-up based on convo with @rnagle today, for #324.
Previous behavior on screens 768px and narrower was to show the site name in both the sticky header in `.nav-left` and in the sticky header's dropdown `.nav-shelf`. Since this would appear twice, we decided it would be better to hide it in the dropdown.
The site name was not removed from `.nav-shelf` because it's visible in the sticky header on screens wider than 768px.
The "Largo Test Site" visible here is in `.nav-shelf`. If the `.nav-left` site name were visible, it would be to the left of the home icon.

Hide the .nav-shelf site name in the dropdown when the .nav-left site name is visible.

---

functions.php
homepages/assets/css/single.css

Only around 20 lines of code here, but they fix #386 and #383.
Creating in a pull request because the following define has to be added to wp-config on production and staging:
```
define('INN_HOSTED',true);
```
This should __replace__ the `INN_MEMBER` constant defined. This leaves `INN_MEMBER` to be definable for sites & child themes hosted on our multisite, but not INN members themselves.

Fixes for homepage image width and INN_MEMBER

---

css/editor-style.css
css/style.css
homepages/assets/css/single.css
less/inc/widgets.less

The editor-style and homepages css changes were created automatically by Grunt watch.
I've included them because they continue to be rebuilt otherwise.
`a.more` no longer bold, to match the INN Member Stories widget's non-bold serif. The Largo Explore Related widget uses bold sans for this, though.
`ul a` no longer has margin-left, because it looked odd
`ul a` now uses sans font family, to match other headlines
`h5`, `h5 a` colors now `@black` to match other widget headlines
For #384

Largo Series Posts widget styles cleanup, plus misc CSS updates from grunt

---

inc/update.php
tests/inc/test-update.php

This creates `largo_force_settings_update` in `inc/update.php`, which can be filled with options whose defaults need to be assured to be set when the 0.3 -> 0.4 updates are run.

Sticky nav by default for #377

---

lib/navis-slideshows/css/slides.css

This is so that slideshows on pages and category landing pages will have full-width images, in the event that the image is narrower than the slideshow container.
This is a fix for CUR-45, but this fix is temporary. The gallery generation code doesn't respect the [gallery option](http://codex.wordpress.org/Gallery_Shortcode#Options) `size="full"` for using larger images, and setting a larger image width in Dashboard > Settings > Media doesn't work. The new setting is reset to 771px wide.

Removing slideshow CSS image-width limitation

---

inc/widgets/largo-recent-posts.php

Changes and new features:
- Thumbnails are now output before headlines, for consistency with pretty much every other Largo display (#400)
- Bylines can now optionally be output (for NPQ)

Recent posts widget feature requests

---

inc/ajax-functions.php

LMP post return now uses number of posts per cat/home from settings

---

inc/widgets/largo-recent-posts.php

This enables top terms as an option in the Largo Recent Posts widget. This was requested for NPQ.

Top Terms in the Largo Recent Posts widget

---

inc/update.php
tests/inc/test-update.php

This commit provides:
- remove the old "Top Story" and duplicate "top-story-2" prominence terms on update
- enable series taxonomy if series were previously used
- enable the series taxonomy and series landing pages if series landing pages were previously used
- stubbed tests for the above
This is for:
- #414 for the duplicate prominence terms
- Adam mentioned the enabling of the series taxonomy, but I can't find a ticket for it.

Update functions for #414 and enabling series and landing pages if they were in use before

---

docs/developers/imagesizes.rst
docs/index.rst

Added documentation for image size crops in Largo.
Could probably just push this up myself, but pull request are fun.
@meredithinn anything else need to be added here?

Developer docs for image sizes used in Largo

---

css/editor-style.css
css/style.css
inc/post-tags.php
less/inc/single.less
lib/options-framework/css/optionsframework.css
options.php
partials/footer-sticky.php
tests/inc/test-post-tags.php

For #434:
- Sticky footer social media buttons are now their own general toggle, and each button can be toggled independently
- Half of a test for largo_post_social_links
- Re-added the email button to the post-top social media buttons using the footer-style email button

Options for the sticky footer social media buttons

---

partials/content.php

A small change: wraps the hero image of posts in the river with an anchor tag that uses the post's link and title.

Clickable hero images in the river view, for #457

---

lib/navis-media-credit/navis-media-credit.php

One line fix for extra slashes being added in the caption field when media is sent to the visual editor from the media library. Should close #465 and associated current.org help desk ticket.

#465 - fix for erroneous addslash() in caption.

---

inc/ajax-functions.php
tests/inc/test-ajax-functions.php
tests/inc/test-post-tags.php
tests/mock/mock-options-framework.php

- of_get_option('cats_home') no longer figures in the LMP query if we're not on the home page
- in tests, of_reset_options() now establishes the defaults instead of completely nuking the options array
- fixed a test that failed because of the previous change

LMP bug fix for #499

---

inc/ajax-functions.php
js/load-more-posts.js
partials/content-series.php
series-landing.php
tests/inc/test-ajax-functions.php

Landing pages were loading partials/content when
partials/content-series is used on landing pages.
generating function that this is a series landing page
determine the dom to return.
is done using it.
We can probably (in the future) overhaul the series page template to
simplify how it asks and controls dom.

Fix LMP dom on series landing pages.

---

inc/taxonomies.php

I did some testing and I couldn't get a largo setup that replicated #399. However, I found another bug that I believe may be the source.
If series are disabled and a user is created, the first time they visit the menu page they will get an option set to hide `add-series` and `add-post-type` on the menu page (because these taxonomies are still registered as 'ghost' taxonomies). If the series are then enabled, they'll be hidden.
The simple fix: If the series/post types are not enabled, be explicit and not allow them as a menu item.
See my comment on:
http://stackoverflow.com/a/8363082/620680
We should still keep an eye on this.

#399 custom tax in menus

---

css/editor-style.css
css/style.css
less/inc/navbar.less

Reported by current.org, the search bar goes off screen on mobile.
I reduced the width of the dropdown by about 50px so that it fits on
320px wide screens.

Fix sidebar overflow on mobile

---

inc/related-content.php
inc/widgets/largo-author-bio.php
tests/inc/test-related-content.php

- `get_series_posts()` and `get_term_posts()` no longer query for `-1` infinite posts in every series associated with the current post, but instead query for the number of posts that will need to be outputted.
- The query for CFTL taxonomy landing pages in each series is now wrapped in a conditional that checks for a cached version of the query and uses that. If the cached query does not exist, it runs a new query and caches it. More details on how that works [here](http://www.wpbeginner.com/wp-tutorials/speed-up-your-wordpress-by-caching-custom-queries-using-transients-api/).
- Unrelated to Largo_Related, fixes a missing argument for is_series_landing() in the Largo Author Bio widget.
- Empty tests for inc/related-content.php
See #671: Largo_Related was querying for all the posts posts …

Decrease Largo_Related resource use

---

inc/widgets/largo-related-posts.php

- Largo Related Posts Widget now uses [largo_excerpt](https://github.com/INN/Largo/blob/0e73daf4b9e6238f248d947458da600662c9b018/inc/post-tags.php#L369) for post text generation
- Largo Related Posts Widget will now have [all the excerpt fallbacks](https://github.com/INN/Largo/blob/0e73daf4b9e6238f248d947458da600662c9b018/inc/post-tags.php#L377-L398) of largo_related
- The excerpt in the related posts widget will be able to be filtered by child themes

Make Largo Related Posts Widget use largo_excerpt instead of $post->post_excerpt

---

inc/widgets/largo-staff.php

This filter allows for arbitrary transformations to the `$users` array used to render the staff roster widget.

Add ability to filter the array of users used in the staff/contributor widget

---

footer.php
partials/footer-before-footer-widget-area.php
sidebar.php
single-one-column.php
single-two-column.php

Adds `nocontent` class to the following areas:
- The footer
- The before-footer widget area
- The sidebar on article pages
- The article-bottom widget area (used for next/previous story buttons and similar)
The `nocontent` class does not have any styles. [Here's how Google interprets it.](https://support.google.com/customsearch/answer/2364585?hl=en)
Google Custom Search Engine results were showing results from pages where the only relevant content was a blurb in the sidebar or the footer.
Reported in YT-24, Largo issue #664

Add `nocontent` class to sidebar, article-bottom, and footer widget zones.

---

inc/plugin-init.php

Until TGMPA [fixes a the bug that shows notices on multi sites to users that can't install plugins](https://github.com/TGMPA/TGM-Plugin-Activation/pull/247), hide uninstalled plugin notices from users who can't do anything about them.

Don't show notices to users who can't do anything about them.

---

inc/update.php

Functions in `inc/update.php` are totally out of order making it difficult to figure out where future update functions should live.
Functions have been organized by when they were added. No new code is included in this pull, just a lot of copy and paste.
For future version releases, we can create a new region header and group all related update functions together there. This should make it easier to keep track of.

Make inc/updates.php cleaner to prepare for future update functions

---

inc/related-content.php

This commit removes the "reverse" functionality of Largo_Related::add_from_query.
The PR message and commit message add a lot of information from Ben Byrne about Largo_Related as he wrote it originally.
The recent changes to Largo_Related were because it was consuming excessive resources when finding a related post. The reason for this was because of some huge queries, which were introduced in https://github.com/INN/Largo/commit/6fb4db3878757767cd5de83e2cae4f3293496147 by Ben Byrne. The code that he wrote was imporessive in its doggedness at finding related posts, and in ordering them. I regret having to take it out, but it was making huge queries.
Ben Byrne writes:
> get_series_posts() and get_term_posts() have posts_per_page set to -1 because we’re not actually trying to fetch posts …

Documentation for Largo_Related's previous functionality.

---

inc/users.php
tests/inc/test-users.php

This PR includes tests!
Updating user metadata prevented the user from displaying in the `[roster]` shortcode.
Previously, updating a user's metadata by saving their profile changed some fields from "" to "off". The roster shortcode checked that those fields were not-empty instead of checking for their false value.
This change was [previously applied in the staff roster widget](https://github.com/INN/Largo/commit/5f77ea918da61e578bdddc0b013738c28c6ad013#diff-42dea38310facb1e34959f63770d8bb7R39), but the widget does not use `largo_render_user_list`.

Bugfix for IW-32, staff roster avatars master

---

inc/post-tags.php
tests/inc/test-post-tags.php

This effectively removes the "more..." or "continue reading" links from the ends of excerpts. Fixes #52.

Deprecate $use_more and $more_link args for largo_excerpt

---

docs/developers/hooksfilters.rst
homepages/templates/top-stories.php

- Adds a filter to the Top Stories homepage template, so that the number of posts on the right-hand column can be modified without duplicating the partial.
- Docs
To prevent the need to duplicate `homepages/templates/top-stories.php` in child themes to change the display of this template. See also #775 and YT-28.

Add filter for top stories homepage template featured posts count

---

partials/largo-header.php
partials/nav-sticky.php

For #664 and YT-24, because GCSE was indexing and delivering search results based on words in the navigation.
Adds the `nocontent` class to:
-  `<div class="sticky-nav-wrapper"`
- `<header id="site-header"`
- `<header class="print-header"`

Adding nocontent class to sticky nav wrapper and Largo <header> elements

---

inc/sidebars.php

We no longer need to define the "Homepage Left Rail" sidebar in `inc/sidebars.php` for a few reasons:
- The new name for the '3col' homepage layout is 'LegacyThreeColumn` and the code removed in this patch would never actually run.
- The "Homepage Left Rail" sidebar is defined in the legacy three column homepage layout.

Remove an unnecessary sidebar declaration from inc/sidebars.php

---

docs/developers/hooksfilters.rst
inc/ajax-functions.php

For #802, creates a new filter `largo_lmp_args` that can be used to manipulate the arguments of the `load_more_posts` ajax call's WP_Query.

Filter the LMP query args

---

homepages/homepage-class.php
tests/homepages/test-homepage-class.php

- the Homepage class checks `is_home()` before enqueueing CSS and Javascripts
- tests
For #791

Stop enqueueing homepage assets in places that aren't the homepage

---

partials/footer-sticky.php

For #825.
If the custom byline is set without a link, then there is nothing to link to in the footer. It is assumed that any coauthor or actual author is meant to be hidden by the use of the custom byline, so the sticky footer does not fill the array of coauthors with coauthors or authors:
if( get_post_meta( $post->ID, 'largo_byline_text' ) ) {
$byline_text = esc_attr( get_post_meta( $post->ID, 'largo_byline_text', true ) );
$byline_link = esc_attr( get_post_meta( $wp_query->post->ID, 'largo_byline_link', true ) );
} else if ( function_exists('get_coauthors') ) {
$coauthors =  get_coauthors( $post->ID );
} else {
$coauthors = array( get_userdata( $post->post_author ));
}
But because the byline link was not set, the partial attempted to render a portion of the partial that depends on …

Do nothing in sticky footer when custom byline is set without link

---

lib/class-tgm-plugin-activation.php

Updates TGM Plugin Activation to 2.5.2 from 2.5.0
https://github.com/TGMPA/TGM-Plugin-Activation/releases/tag/2.5.2
Recommended by TMGPA maintainer @jrfnl in the comments on #773, the last time we updated this.

Use TGM Plugin Activation 2.5.2, the latest GitHub hotfix release.

---

inc/related-content.php
tests/inc/test-related-content.php

Largo_Related now uses the correct query to catch series landing pages.
Tests for Largo_Related's:
Largo_Related bugfixes for #841, Test coverage for #782.

Largo_Related tests and bugfixes

---

inc/update.php

For #854.
This pull request adds a check to the `largo_update_admin_notice` function to check if the current user can manage the network before printing the update message.

Don't show the Largo update message for users that can't update

---

category.php
docs/users/themeoptions.rst
inc/taxonomies.php
options.php

- New option "Hide the featured posts area on category pages?" `hide_category_featured` in Theme Options > Layout Options
- `hide_category_featured` if true hides the presence of the featured posts area on category pages
- `hide_category_featured` if true causes `largo_category_archive_posts` to not modify `posts__not_in` in `$wp_query`
- the featured posts query in the category moves inside the `hide_category_featured` conditional on category pages
- User-facing docs
For #860 and Catalyst Chicago's [HELPDESK-337](http://jira.inn.org/browse/HELPDESK-337)
Because not everyone wants to use featured posts in the category.

Add theme option to disable the featured posts area on category pages

---

category.php
inc/taxonomies.php

This is for #869.
What this pull request does:
- Refactors the featured posts area at the top of the category template so that it's easy to follow what markup gets printed and under what circumstances.
- Fix the erroneous closing `</div>`'s which were printed when no featured posts were available, resulting in a broken category archive page layout.

Fix erroneous closing div tags on category template

---

homepages/templates/top-stories.php

Re-inserts a closing `>` on a `<div>` in the homepage Top Stories template [lost in 0.5.2](https://github.com/INN/Largo/commit/090c5f73d162dcbb9ad9a32cf2e5a65806845b45).
Without the `>` on the `<div`, the `<h5>` created to contain `largo_top_term()` becomes part of the `<div` tag:
This breaks the styles on the top tag.
For [HELPDESK-339](http://jira.inn.org/browse/HELPDESK-339)

Fix missing > in homepages/templates/top-stories.php

---

inc/widgets/largo-recent-posts.php

- Removes read-more link display from the widget
- Removes controls for showing the read-more link in the widget settings
- Removes the setting from the widget defaults and settings
I tested this on NPQ's front page, which has the absolute highest concentration of Largo Recent Posts widgets in existence. There were no errors.
This doesn't trigger any changes in the tests, because we have no tests for widgets.
This doesn't trigger any changes in docs, because the docs for this widget are kind of general: https://largo.readthedocs.org/users/sidebarswidgets.html#custom-widgets
> - **Largo Recent Posts** - A powerful widget to show recent posts in various formats with the option to limit by category, tag, custom taxonomy term and/or author.
Because the read-more link is deprecated and …

Remove 'Show read more link?' in Largo Recent Posts widget

---

inc/widgets/largo-author-bio.php

- defines an empty method `form()` on the Largo Author Bio widget.
For #641.
In [`wp-admin/includes/widgets.php`](https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/widgets.php#L249-L252):
```php
<div class="alignright<?php if ( 'noform' === $has_form ) echo ' widget-control-noform'; ?>">
<?php submit_button( __( 'Save' ), 'button-primary widget-control-save right', 'savewidget', false, array( 'id' => 'widget-' . esc_attr( $id_format ) . '-savewidget' ) ); ?>
<span class="spinner"></span>
</div>
```
`$has_form` is defined [earlier in the same file](
```php
$has_form = 'noform';
...
if ( isset($control['callback']) )
$has_form = call_user_func_array( $control['callback'], $control['params'] );
else
echo "\t\t<p>" . __('There are no options for this widget.') . "</p>\n"; …
```

Add empty form() to Largo Author Bio widget so it has a save button.

---

inc/update.php
tests/inc/test-update.php

- On every time updates run, `largo_replace_deprecated_widgets` will run.
- New function `largo_replace_deprecated_widgets` that replaces a list of widgets with new widgets. Configuration is via the `$upgrades` array in `largo_replace_depracated_widgets`, and is currently set to update `largo-footer-featured` and `largo-sidebar-featured` with `largo-featured`, which was introduced in v0.4.
- Tests in general for `largo_replace_deprecated_widgets`
- `largo_instantiate_widget` now returns an array with the slug and number (2-indexed :cry: ) for the successfully-created widget and its new place in the sidebar (0-indexed):
array(
'id' => 'largo-featured-5',
'place' => '4'
)
- Bugfix in `largo_instantiate_widget` for #728 where it was not checking `widget_widget-slug` in the options table, but …

Migrate old featured posts widgets to the Largo Featured widget, and bugfixes

---

inc/enqueue.php
options.php

https://developers.facebook.com/docs/ads-for-websites/website-custom-audiences/getting-started#install-the-pixel
Facebook loads this pixel to allow audience conversion and passing of information.
* NEW OPTION in database `fb_tracking_pixel` using the options framework. 
* *Note for Changelog*
* Adds new script enqueued in `inc/enqueue.php` in the site footer if option is set
I just added the base tracking of "pixel initiated" blanket to the site (loads on every page). When a logged in facebook user loads the site, information is passed via the pixel. 
In the future, additional parameters can be passed including search queries, the category of content (i.e. Environment) and other page meta. This allows deeply targeted ads such as "Show this ad to Facebook users who have read an …

add fb tracking pixel

---

inc/ajax-functions.php

Fixes #954 where the non-landing page series archive's Load More Posts button was using `partials/content-series.php` instead of the archive partial, leading to incomplete posts.

Use content-archive partial for LMP in series without a landing page

---

docs/developers/hooksfilters.rst
home.php
homepages/templates/legacy-three-column.php

Adds the following actions to the Legacy Three Column and the other homepage layouts:
- `largo_before_sticky_posts`: Runs before the sticky post would be rendered
- `largo_after_sticky_posts`: Runs after the sticky post would be rendered, before the homepage bottom area.
- `largo_after_homepage_hottom`: Runs after the homepage bottom area.
These run before the termination of the main column, so any widgets placed here will be beside the sidebar, not below it.
To avoid making duplicate partials for [HELPDESK-438](http://jira.inn.org/browse/HELPDESK-438).
To make it easier to add things to a relatively-unmodified homepage, without authoring a whole new homepage template.
PR against master because this is a hotfix.

Add a bunch of actions to the homepages

---

inc/widgets/largo-about.php
inc/widgets/largo-author-bio.php
inc/widgets/largo-disclaimer-widget.php
inc/widgets/largo-donate.php
inc/widgets/largo-explore-related.php
inc/widgets/largo-facebook.php
inc/widgets/largo-featured.php
inc/widgets/largo-follow.php
inc/widgets/largo-footer-featured.php
inc/widgets/largo-image-widget.php
inc/widgets/largo-post-series-links.php
inc/widgets/largo-prev-next-post-links.php
inc/widgets/largo-recent-comments.php
inc/widgets/largo-related-posts.php
inc/widgets/largo-series-posts.php
inc/widgets/largo-sidebar-featured.php
inc/widgets/largo-tag-list.php
inc/widgets/largo-taxonomy-list.php
inc/widgets/largo-twitter.php

Per @aschweigert’s request, resubmitting #969 against master branch.
https://markjaquith.wordpress.com/2009/09/29/using-php5-object-constructors-in-wp-widget-api/
https://wiki.php.net/rfc/remove_php4_constructors
Resolves issue #949

resubmitting PHP4 widget constructor removal against master branch

---

inc/ajax-functions.php
tests/inc/test-ajax-functions.php

- checks `LARGO_DEBUG` for whether to use `/js/load-more-posts.min.js` or `/js/load-more-posts.js` in the LMP enqueue.
This change can't be tested without a way to change constants at runtime. I left a note in the test.
For #967.

Use minified version of LMP javascript, if LARGO_DEBUG isn't true. 

---

inc/ajax-functions.php
inc/post-templates.php
partials/content-search.php
partials/content.php
search.php
tests/inc/test-ajax-functions.php
tests/inc/test-post-templates.php

Functionality: 
- `largo_load_more_posts_choose_partial()`: 
- Adds tests for `largo_load_more_posts_choose_partial()`
- `largo_load_more_posts_choose_partial()` doesn't require `$_POST['is_series_landing']` to be set in order to run.
- `largo_load_more_posts_choose_partial()` now checks inside the `query_vars` property of the `WP_Query` object, not various properties of the `WP_Query`. This should fix the problem where it was returning 'home' for categories and author archives.
- `largo_load_more_posts_choose_partial()` now returns 'search' on search pages, meaning that the `partials/content-search` partial will be loaded on search. Since Largo does not ship that partial, this will fall back to `partials/content.php`.
- `largo_load_more_posts_choose_partial()` and `search.php` now use …

Correcting bug in largo_load_more_posts_choose_partial

---

inc/post-tags.php

Because galleries, videos, and optionally embeds set a featured image, the check for a thumbnail should be last. this moves it to the last position.
We don't have any styles for `.is-embed` in Largo, and the lone style for `.is-gallery` makes the background of the hero transparent in color. This shouldn't affect any child themes negatively.
I'm filing this against master because it's presumably something we'll want to ship before 0.5.4.
For #1026 and [VO-6](http://jira.inn.org/browse/VO-6)

Move the is-image check to the end of largo_hero_class

---

options.php

- Adds links to the Read The Docs pages for the Theme Images page in the Theme Options.
- Sets the default header option to use the text header, since presumably people won't have immediately uploaded images.
For #181.

Make default header option to not use images

---

docs/developers/grunt-commands.rst
docs/developers/index.rst
docs/developers/intro-command-line.rst
docs/developers/setup-documentation.rst
docs/developers/setup.rst

- Adds `npm install` to the developer umbrella setup instructions
- Some style fixes in the developer setup and the developer just-for-docs setup instructions.
For #953. People who try to run grunt commands will experience an unhappy surprise.

Developer docs: Adding 'npm install' and some style fixes.

---

docs/developers/hooksfilters.rst
docs/developers/index.rst

- Adds docs for `largo_partial_by_post_type` and `largo_lmp_template_partial`
- Slightly better docs for `largo_lmp_args`
- Formatting cleanup of `hooksfilters.rst` for readability
- Adds the Hooks and Filters page to the developer docs index.
For #1028, because these are important when adding custom partials.

Add docs for Load More Posts filters

---

partials/archive-category-primary-feature.php
partials/archive-category-secondary-feature.php

Uses the second argument of `post_class()` to specify that the classes to be output are from the current post, not for the `global $post`.
For #1052.
Posts had the wrong classes, most noticeably because the post ID in the classes was not the post ID in the html element ID.

Use the post ID argument on post_class() in the hierarchical archive pages

---

inc/header-footer.php

If the check for `INN_logo` is case-sensitive, then Largo will attempt to redefine an existing function if the child theme has defined their own `inn_logo` function.

Use lowercase inn_logo for function_exists check

---

inc/widgets/largo-recent-posts.php
partials/widget-content.php

- adds option in the Largo Recent Posts widget to show the icon set for posts in the Post Types taxonomy, if the taxonomy exists and the option is checked
- if the post type icon is enabled in the widget, attempt to display the icon inside the post title's h5.
If a post type icon is not set for the post, then no post type icon will display.
The icon is inside the `h5` and the `a`, making sure that the icon is grouped with the title in the layout. However, the icon may still wrap onto a new line. There is nothing we can do about this, because the same thing would happen if the icon was replaced with a word: the headline would wrap.
(Well, we could remove the icon from the `h5 a` and put it someplace else in the layout, with appropriate fixed-positioning styles.)
Using RNS styles:
Because …

Add option to display post type icons on the Largo Recent Posts widget.

---

docs/developers/hooksfilters.rst
inc/post-tags.php

- Filter the output of `largo_byline()` before the edit link is appended to it
- Docs
To allow child themes to prepend or append content to the output of the byline function.
For #1070 and [RNS-107](http://jira.inn.org/browse/RNS-107).

Filter the output of largo_byline

---

docs/users/themeoptions.rst

Update outdated instructions for settings in Theme Options > Basic Settings, deleting some that no longer exist at all, and moving the Menu Options stuff to the new Navigation tab, plus just adding some bold markup for consistent use of bold.

Jack docs users themeoptions basic settings

---

inc/post-tags.php

- Uses `esc_url` instead of `esc_attr` for the permalinks passed with the Twitter and Facebook share buttons
- Uses `urlencode` instead of `esc_attr` for the post title passed with the Twitter share button.
For #1076 and [HELPDESK-537](//jira.inn.org/HELPDESK-537/)

Escape the URLs on the share buttons, and the text on the Twitter button.

---

inc/post-templates.php

We already have the logic for what to do if $custom_field is empty, so we can make use of that and just not set $custom_field in the even that $post is not an object.
For #1078 and because it was cluttering up my logs when I was looking for something else.

Allow get_post_template to not use get_post_meta if global $post isn't an object

---

inc/metabox-api.php
inc/post-metaboxes.php
inc/related-content.php

- adds 'none' option to largo_top_tag_display metabox function
- changes the validation function for the top term from `intval` to `sanitize_key` because "None" cannot have an id of `'0'` because `'0'` and `0` and `''` are falsy and therefore _largo_meta_box_post_save will remove the option instead of saving it
- change largo_top_term so that it outputs `''` if the top term option is `'null'`
For #1082 and [RNS-127](http://jira.inn.org/browse/RNS-127).

Support a "None" option for the top term

---

inc/post-tags.php
inc/users.php
options.php
partials/author-bio-description.php
partials/author-bio-social-links.php

- Adds "Job Title" to the fields supported by Co-Authors Plus
- Adds the job title to the output of `largo_byline` if Co-Authors Plus is enabled
- Adds the job title to the output of `largo_byline` if Co-Authors Plus is not enabled
- Does not link the job title to the author's byline page
- Does not affect `largo_author_link`
- Adds the option to show a coauthor's email address. There doesn't appear to be a way to set a default, with [how the metabox is constructed](https://github.com/Automattic/Co-Authors-Plus/blob/f4da16bb59ef692d02db315771b238af7f75d8a4/php/class-coauthors-guest-authors.php#L669), so this will default to hiding the user's email address.
- Makes `partials/author-bio-social-links.php` respect the coauthors option. This will only affect coauthors users. This does not …

Add job title to fields accepted by coauthors

---

inc/post-tags.php

The Twitter 'via' attribute output is set in the following order
- The single coauthor's twitter handle, if it is set
- The site's twitter handle, if there are multiple coauthors and a site twitter handle
- The single user's twitter handle, if it is set
- The site's twitter handle, if it is set and if there is a custom byline
- The site's twitter handle, if it is set
- No 'via' attribute if no twitter handles are set or if there are multiple coauthors but no site twitter handle
For #1088 and [WE-81](http://jira.inn.org/browse/WE-81).

Better fallback cases for the 'via' twitter handle in largo_post_social_links

---

inc/post-tags.php

- Don't output job title if custom byline text is set
- Add a space between the comma and the job title on non-coauthors
I saw it happening on a testing vagrant site.
This bug was introduced in #1098 for #1097.

Don't output job title if custom byline text is set

---

inc/related-content.php
inc/widgets/largo-related-posts.php

- Don't duplicate the date
- Do call `largo_byline` with the argument that doesn't suppress the output of the date.
- Change the conditional determinant inside the Related Posts function, because `count(false)` returns `1`. [Yep.](https://secure.php.net/manual/en/function.count.php)
For #1110 and http://jira.inn.org/browse/WE-85

Fix small problems in Recent Posts widget

---

partials/author-bio-social-links.php

- Uses 'this author' if the author's first name is not available.
This button wasn't always displaying a username, because not all users set their "first name" field in the WordPress user settings. 
For http://jira.inn.org/browse/WE-86

Use 'this author' instead of any other reference in the author bio read-more link

---

inc/post-tags.php
tests/inc/test-post-tags.php

Please don't use esc_attr for post titles that are part of URLs.
- replaces several `esc_attr` in `largo_post_social_buttons` with `rawurlencode`: https://secure.php.net/manual/en/function.rawurlencode.php
Because the changes in https://github.com/INN/Largo/pull/1077/files were undone by the redo of the post social buttons.
Write tests for these buttons, perhaps as part of the `largo_post_social_links` redo in #219.

Use rawurlencode for maximum redundancy.

---

archive.php
category.php
partials/content-roundup.php
partials/content-rounduplink.php

- Create partials for use in Largo:
- `content-rounduplink.php`: no byline, very little in the way of content. This is essentially a rehash of the `argolinks` partial removed for #926.
- `content-roundup.php`:
- displays whole `the_content()` in archives, as the content will be primarily shortcodes and thus will not be rendered in `largo_excerpt`. 
- byline is output, buy `.visuallyhidden`
- In `archive.php` and `category.php`, use `largo_get_partial_by_post_type` for the partial selector, so those can be filtered with `largo_partial_by_post_type`.
A demonstration of the `content-roundup.php` partial in the archive:
Generated saved links, with one edited to have a description and link:
While the Link Roundups plugin can use the filter `largo_partial_by_post_type`, it can't provide …

Improve support for Link Roundups in archives

---

inc/post-tags.php

This PR is a shot in the dark. I don't know why the behavior described in #1117 is happening.
- makes sure that `$via` is `''` before trying to use the `post_author`'s Twitter handle
- Doesn't display the `post_author`'s Twitter handle in the "More" social menu if Co-Authors Plus is present and active.
Because #1117 and http://jira.inn.org/browse/WE-87

Attempted fixes for #1117, where post_author twitter account is used instead of coauthor

---

archive.php
docs/developers/hooksfilters.rst

- creates new filter `largo_archive_rounduplink_title` and runs the title of `archive.php` through that when the archive is for the `rounduplink` post type.
- docs for same in `developers/hooksfilters.rst`, including example function.
For #1123 and http://jira.inn.org/browse/GIJN-35

Make the archive.php rounduplinks title filterable

---

docs/developers/hooksfilters.rst
inc/post-tags.php

- Adds filter `largo_post_social_more_social_links` on the `$more_social_links` array in `largo_post_social_links()`, adding the ability to add new menu items with array operations
- Docs in hooksfilters.rst with example filter.
For #219 and [NQ-127](http://jira.inn.org/browse/NQ-127)

Filter the "More" menu in largo_post_social_links

---

docs/developers/hooksfilters.rst
inc/sidebars.php
single-one-column.php
single-two-column.php

- Replaces the article-bottom widget area call in the single one- and two-column templates with the action `largo_post_bottom_widget_area`
- Adds new function `largo_post_bottom_widget_area` to output the article-bottom widget area, hooked on `largo_post_bottom_widget_area`. (Same name for function and action.)
- Docs in docs/developers/hooksfilters.rst
To make it easier to modify this area.

Make the article-bottom widget area into an action

---

inc/post-tags.php

- Sets the variable containing the future output of `largo_post_social_links()` to the return of the filter `largo_post_social_links`
Because we had a filter that wasn't actually affecting the output on the page.
For http://jira.inn.org/browse/NQ-127

Use the output of the largo_post_social_links filter

---

inc/post-tags.php

- Converts all HTML entities, including numeric ones, to their UTF-8 characters before encoding them with `rawurlencode`. The flags come from this comment: https://secure.php.net/manual/en/function.html-entity-decode.php#93378
#1134 and http://jira.inn.org/browse/WE-92

Use html_entity_decode on twitter title in share text

---

inc/widgets/largo-staff.php

- Adds the authors' first name, last name, comma, job title to the alt attribute of avatars in the staff list widget. (get_avatar does not respect the image's alt text, for whatever reason. :black_joker:)
http://jira.inn.org/browse/HELPDESK-576

Add name and job title to the alt attribute of images in the Largo Staff Widget

---

docs/users/posting.rst

Major overhaul of the posting.rst page to better document how to use all the features of the Post screen, and to fix some legacy language there. Added a bunch of details on Module Wrapper and Featured Media, and more complete explanation of entering taxonomies. 
This work was based on https://github.com/INN/Largo/issues/381, a milestone for Largo 0.5.5.

Jack's edits for Largo/docs/users posting.rst

---

404.php
options.php
partials/content-not-found.php
searchform.php

- When used on a search page, the search form partial will display the search query. (Does not affect the header search; that does not use `searchform.php`
- The 404 page shows an optional text message supporting basic HTML under the search form, which is set in the theme options under Advanced options.
- `partials/content-not-found` displays the 404'd URL in a `<code>` element before the search box if the page is a 404. Otherwise, it continues to display "Apologies, but no results were found. Perhaps searching will help.'"
Here's an example with a successful search, showing the query in the search box:
An unsuccessful search, showing a different text suggesting running a different search:
A 404 page, showing the requested URL:
A 404 page on a child theme, showing custom text and HTML …

404 page improvements

---

docs/users/sidebarswidgets.rst

The sidebarwidgets page on http://largo.readthedocs.org/users/sidebarswidgets.html was woefully incomplete and out of date, and revising it has been a high priority prior to the coming release of Largo 0.5.5. (see: https://github.com/INN/Largo/issues/847)
Legacy language and formatting was cleaned up considerably and normalized. Sections were added for Largo widgets that weren't in the docs, and other sections were revised for accuracy, spelling, language, etc. Formatting was applied for better usability. Basically this is a complete revamp of the page.
It was suggested to create pages for each widget, so as to provide more details, screenshots, etc., and that can certainly be done. Since it was a high priority to fill in missing information and to correct errors, I chose to first make …

Revise sidebarwidgets.rst to add details on Largo widgets, and fix errors

---

series-landing.php

Resets the global $post with `wp_reset_postdata()` after the sidebar.
Widgets in the sidebar of the series landing page can mess with the global `$post` variable, causing the the series landing page footer to be drawn from a post that is not the series landing page. If the post mismatches, then contents of the footer are unreliable, and may not match the resired setting of non, sidebar, or custom HTML.
This doesn't affect the landing page's LMP query, because the LMP query is encoded into the page before the sidebar is output, when the LMP partial is gotten.
This doesn't account for protections to widgets in the footer, because as far as I know Largo doesn't recommend or support putting post-dependent widgets in the global footer context. Plus, post-dependent widgets wouldn't be put …

Fix series landing page footer using wrong global $post after the sidebar is output

---

archive.php
category.php
inc/widgets/largo-recent-posts.php

- Add posts from the global `$wp_query` to the list of posts from `$shown_ids`, and use the combined list as the `post__not_in` argument on the Recent Posts query.
Adding posts in archive pages to `$shown_ids` will add those posts to the posts excluded from the Load More Posts query by the `largo_load_more_posts_data` JSON object. If posts from the initial page load are excluded from the LMP query, it has the effect of removing the first page of results from the LMP query, causing the second page to be considered the first page. The posts returned by the first LMP button-press will then be the third page of result.
Therefore, instead of getting posts from `$shown_ids`, get them from the `$wp_query->posts` array.
For [RNS-172](http://jira.inn.org/browse/RNS-172) and #1149.

Ignore posts from main query in Largo Recent Posts widget

---

inc/related-content.php

- Adds the top term to the classes output by `post_class`, using slugs in the formula `top-term-$taxonomy-$term`
- Does not add the top term if the top term is not set.
For #1119 and [RNS-159](http://jira.inn.org/browse/RNS-159).

Add top term to the post classes

---

docs/developers/constants.rst
functions.php
inc/header-footer.php
inc/update.php
tests/inc/test-update.php

- Notes that `SHOW_STICKY_NAV` is deprecated in the constants list in the dev docs
- Since the theme option `show_sticky_nav` was removed in #1024, ~~uses `sticky_nav_display_article` as an approximation of whether or not the sticky nav should be displayed. This is a temporary fix, and is not meant to accurately reflect whether or not the sticky nav should be displayed. This is only to avoid the sticky nav never displaying.~~ this PR defines `SHOW_STICKY_NAV` as false.
- Removes the update function for `show_sticky_nav` in `inc/updates.php`
- Removes the test for the update function's `show_sticky_nav` updater
- Marks `largo_sticky_nav_active` as deprecated as well, because that function existed to return `SHOW_STICKY_NAV`. `largo_sticky_nav_active` has no tests.
This is a compatibility …

Deprecate the constant SHOW_STICKY_NAV

---

docs/users/taxonomies.rst

- add term descriptions section, note that HTML should be valid.
- remove a 'simply'
Because we don't have this warning in the docs anywhere.

Warning about HTML in the term descriptions.

---

docs/users/plugins.rst
inc/ajax-functions.php
inc/post-templates.php
tests/inc/test-ajax-functions.php

- Replaces Argo Links with Link Roundups in the list of recommended plugins
- Removes direct support for the argolinks partial in `largo_load_more_posts_choose_partial()`; if support is desired it should be re-added with the `largo_lmp_template_partial` filter
- Removes direct support for the argolinks partial in `largo_partial_by_post_type()`; if support is desired it should be re-added with the `largo_partial_by_post_type` filter
- Removes some comment references
For #926

Last scrub of Argo Links from the repository

---

docs/users/posting.rst

Updated posting.rst to add some links to the relevant docs in the Largo User's Guide for options to add custom classes in posts. This addresses some gaps in the Largo Docs identified in https://github.com/INN/Largo/issues/778

Add links to Largo User Guide for text formatting options

---

feed-mailchimp.php
homepages/templates/top-stories.php
homepages/zones/zones.php
inc/post-tags.php
inc/widgets/largo-related-posts.php
partials/archive-category-primary-feature.php
partials/content-search.php
partials/content-series.php
partials/content.php
partials/sticky-posts.php

In all places where Largo calls `largo_excerpt` with more than 2 args, the 3rd and 4th args are set to `null`
The default args are set to `null` as well.
This prevents every page load causing a long repetitive list of the debug message listed in #1214, when `WP_DEBUG` is true.

Replace deprecated arguments in largo_excerpt with null

---

docs/users/themeoptions.rst

Add details to the docs/users/themeoptions.rst page to provide more complete guidance on Theme Images, where they appear, and what are the recommended sizes. Also add links to the Largo Guide for Users for more details and screenshots.

Edits to Docs/Users/Theme Options page

---

category.php
docs/developers/hooksfilters.rst

- add `largo_after_category_river` action to match existing `largo_before_category_river`
- add `largo_category_after_description_in_header` action, before `get_template_part('partials/archive', 'category-related');`
- docs

Add some actions in category archive pages

---

inc/featured-media.php

- Adds `term.php` to the list of admin URLs that the Largo featured media javascripts should be enqueued upon
- Makes sure that WordPress' Javascript media things are loaded: https://codex.wordpress.org/Function_Reference/wp_enqueue_media
Because the edit url in the admin changed for terms in 4.5, from one of `'edit.php', 'edit-tags.php', 'post-new.php', 'post.php'` to `'term.php'`.

Re-enable term featured media after 4.5

---

inc/dashboard.php

Updated the Knowledge Base link in the **Project Largo Help** section of the Largo Dashboard to point to the new Knowledge Base on FreshDesk (http://support.largoproject.org/support/solutions).
The Knowledge Base link was pointing to the deprecated Confluence knowledge base (http://confluence.inn.org/display/LKB/Largo+Knowledge+Base) which we're not using anymore.

Update link to the new Knowledge Base url in Largo Dashboard

---

archive.php
docs/developers/hooksfilters.rst

- adds a conditional `elseif ( is_post_type_archive() )  {` to the section at the start of the file:
- sets the title to `post_type_archive_title()`
- sets the feed url to `'/feed/?post_type=' . urlencode($wp_query->query_vars['post_type'])`, which will look like `http://example.com/feed/?post_type=roundup`
- wraps the feed url for both the rounduplink and generic cases with [`site_url()`](https://codex.wordpress.org/Function_Reference/site_url), to make them point to the correct URL if the site is not hosted at the root of its domain.
For #1231, makes sure there's a title for all `post_type` archives.
Adds site_url because it's a better practice than to rely on `/` being the root of the site.

Add a case for the generic post_type in archive.php

---

tests/inc/test-helpers.php

- the formerly-nonexistent facebook test user `abcdefghijklmnopqrstuvwxyz12 ` is now the currently-nonexistent user `fb8c57ff40dda4b6898ae049d8298584`
- because someone created an account for `abcdefghijklmnopqrstuvwxyz12 ` and our tests were failing.
https://github.com/INN/Largo/issues/1233

Change test nonexistent FB user to a pseudorandom string

---

.travis.yml

• Simplifys the build matrix to use WordPress branches rather than tags so the most recent version of each branch is tested
• Adds WordPress versions 4.5.x and "trunk", branch `4.5` and `master` respectively
• Switches from SVN to Git checkout of WordPress "develop" repo as the Git clone is ~25% faster than an SVN checkout
• Moves the "common" environment variables `WP_TESTS_DIR` and `WP_CORE_DIR` from the the build matrix to export during `before_script` 
Hopefully this speeds up your Travis CI tests a little and facilitates a little less maintenance of `.travis.yml` as WordPress releases new versions 😄

Travis CI: Simplify config and update tested WordPress versions

---

docs/developers/hooksfilters.rst
search.php

- two actions for GCSE searches: before and after
- three actions for non-GCSE searches: before, in middle and after
- docs for above
#1235, to lessen reasons for modifying the search page.
In the future, we may want to break the search page up even further.

Add 5 new actions to the search form, and docs

---

inc/featured-media.php

- on the `admin_enqueue_scripts` action `largo_enqueue_featured_media_js`, if the passed hook is `term.php`, go ahead and try to find the term featured media post
- when doing that, don't assume anymore that the taxonomy will be in the URL parameters. Get the taxonomy from `get_current_screen` instead.
#1225 didn't go far enough. It [added term.php](https://github.com/INN/Largo/pull/1225/files) to when `largo_enqueue_featured_media_js` would fire, term.php being [introduced in 4.5](https://codex.wordpress.org/Version_4.5) ([discussion thread](https://core.trac.wordpress.org/ticket/34988)), but didn't add `term.php` to the match slightly further down inside that hook. And it didn't account for the `action` parameter being removed from the term edit url. 
This is a PR against master, and …

Wordpress 4.5 compatibility for detection of term featured media post

---

functions.php

Per issue #844 I ran Theme Check on Largo. 
This pull request addresses a "Required" item reported by Theme Check, noting that the theme uses the <title> tag but doesn't include theme support in functions.php. So I've made that small change where I hope it makes sense (just let me know if it would be better elsewhere in the file and I'll fix).
I tested this using the WP test content library and see no issues.
It's a fairly trivial improvement, so I'm sure it can wait.

Per issue #844 - adds theme support for <title> , as reported by Theme Check

---

inc/users.php

Fixes "Required" item listed in issue #844 `get_currentuserinfo()` found in the file users.php. Deprecated since version 4.5. Use `wp_get_current_user()` instead. Line 144"
Checks that current WP version is 4.5 or higher only uses `wp_get_current_user()` if true, otherwise still uses `get_currentuserinfo()`.
Performed a diff of the var_dump of both get_currentuserinfo() and wp_get_current_user(), and they're identical (as expected).

Update get current user to wp get current user

---

inc/post-metaboxes.php

*This PR is an update of https://github.com/INN/Largo/pull/1252, but applied against the master branch as a hotfix*
Fixes issue identified in #956 
Prominence Terms added via `/wp-admin/edit-tags.php?taxonomy=prominence` are not displayed in the add/edit post screens.
This appears to be caused by the for loop that creates $termList in https://github.com/INN/Largo/blob/master/inc/post-metaboxes.php#L314
`$largoProminenceTerms` and by extension, `$slugs` only pull the default options set in the theme at https://github.com/INN/Largo/blob/master/inc/taxonomies.php#L90, so the for loop is only adding items to the display which exist in the default theme set.
I'm not sure if this loop was intended for something else, but removing it entirely and renaming `$terms` to `$termList` fixes the issue.

making Post Prominence tax items created via wp-admin visible on post add/edit screens

---

category.php

- `category.php` will use the output of the `largo_get_partial_by_post_type` function instead of always rendering `partials/content-archive.php`
For consistency with `archive.php` and because this is the intended used of that function.

Make category.php use the largo_get_partial_by_post_type partial

---

js/navigation.js

- When the sticky nav is set to display on the homepage, the height of the container element shall be nothing. 
- Merge the cases for "It's a phone" and "We're hiding the main nav on an article and only displaying the sticky nav" because they're doing the same things.
- but continue running `this.stickyNavScrollTopHide()` on the "Always show sticky navs" case
- No matter the value of `Largo.sticky_nav_options.sticky_nav_display`, sticky nav displays. This is true in current `develop` branch. I'm going to add this note to #1260 for another PR's fix.

Prevent sticky hav container from having height set before the nav is set to display

---

archive.php
category.php
docs/developers/hooksfilters.rst
partials/home-post-list.php
series-landing.php

give ourselves a hook to add content at arbitrary locations in archive page loops (after the Nth post, insert an ad or signup box, etc.)
This is needed for MS Today so it will be a hotfix in the master branch

add counters to main loop on archive pages

---

category.php
partials/content-not-found.php

- If the category has posts in the featured header, do not output `partials/content-not-found.php` if there are n < 6 posts in the category and the featured header is displayed.
- In that partial, don't output `Page Not Found` if it's not a 404. Examples of where this situation may occur:
- `index.php`
- `archive.php` and `category.php` if no posts match the query
- `partials/home-post-list.php`
Using the same site as the original screenshot in #898 for these screenshots.
This is why the changes to `partials/content-not-found.php`:
After those changes: 
A 404 in this PR; nothing's changed:

Fix for "Page not found" on categories with hierarchical header and < 5 posts

---

inc/open-graph.php

to catch things like quotation marks getting through. This is needed for RNS

proper escape excerpts and descriptions in og tags

---

lib/options-framework/css/optionsframework.css

Headings in Theme Options were missing padding
**Before:**
**After:**

adding padding around Theme Options tab headers

---

inc/nav-menus.php

Fixes #1083 
This PR adds a function that fires on the `wp_nav_menu_objects` hook, checks if we're building the `dont-miss` location's menu, and then fires the existing `wp_nav_menu_{$menu->slug}_items` filter call, using the dynamically selected menu slug.
I'm not in love with this solution, but it's very functional and I think can solve the current issue in #1083 until we're able to loop back and rethink this on a larger scale.

updated filter to fire on any menu name in that dont-miss location

---

inc/related-content.php
partials/archive-category-related.php
tests/inc/test-related-content.php

- `largo_get_related_topics_for_category()` now outputs empty string if there are no related topics
- `partials/archive-category-related.php` is changed to match
- spaces converted to tabs in `largo_get_related_topics_for_category()`.
Changes in `largo_get_related_topics_for_category` for #1288:
- outputs empty string instead of an empty `<ul></ul>` because if we wanted to keep detecting the HTML elements in the partial, `partials/archive-category-related.php` would have to match the output of that function to the output of `apply_filters( 'largo_related_topics_title_ul', __( 'Related Topics:' , 'largo' ) );`, wrapped in a `ul li strong`.
- added some notes to stubbed test for this function.
Spaces to tabs to align this with the WordPress PHP code standards.

Do better detection of no related topics in Largo's category template

---

inc/widgets/largo-recent-posts.php

solves #1219 
If a post is displayed in the Recent Stories / River View, then it will not display on the Regular / Top Stories view in Related Posts Widgets if "Avoid Duplicate Posts" is checked.
Posts in the Recent Stories / River View should not affect the display of stories in the widget areas of the Regular / Top Stories view.
The `$shown_ids` variable is already being passed to `widget()`, containing the post IDs that have been displayed thus far on the page.
This PR removes the additional check against `$wp_query->posts` which is adding posts from the river view into the list of excluded ids.

Display posts hidden in Recent Stories list when "Avoid Duplicate Posts" is checked

---

inc/related-content.php
inc/update.php
tests/inc/test-related-content.php
tests/inc/test-update.php

Fix broken tests in PHP 5.5

---

homepages/templates/top-stories.php
homepages/zones/zones.php
partials/content-roundup.php
partials/content-series.php
partials/content-single.php
partials/content.php
partials/widget-content.php

solves #1092 
This PR adds checks to catch empty `largo_top_term()` results and suppress the `<h5 class="top-tag">` from being printed.

Don't display empty empty h5.top-term tags if largo_top_term() returns ''

---

inc/editor.php

fixes #790 
Span tags used to markup underline and text colors via TinyMCE are being stripped in https://github.com/INN/Largo/blob/6a4eb174c54ddf3dcbf3c3aba36f7a1efc6d7b46/inc/editor.php#L71-L80
Update logic to remove span tags if they have no class _and_ no style attribute - leaving the style markup for underline & text color alone

only remove <span> if it has no class & no style attribute

---

inc/editor.php

per #670 
There is no need to use an H1 in the body of a post with this theme. Doing so can only negatively effect the site's SEO rankings.
Removing the Heading 1 formatting option from the format dropdown entirely

remove Heading 1 from format dropdown

---

inc/byline_class.php

For #1310, and for Chicago Reporter where this was noticed.
Before:
```html
<h5 class="byline"><a class="url fn n" href="http://chicagoreporte.wpengine.com/author/leeandra-khan/" title="Read All Posts By LeeAndra Khan" rel="author">LeeAndra Khan</a> <time class="entry-date updated dtstamp pubdate" datetime="2016-07-27T10:19:01+00:00"><span class="published">Published </span>July 27, 2016</time> <span class="edit-link"><a href="http://chicagoreporte.wpengine.com/wp-admin/post.php?post=919103&amp;action=edit">Edit This Post</a></span></h5>
```
After:
```html
<h5 class="byline"><span class="by-author"><span class="by">By</span> <span class="author vcard" itemprop="author"> <a class="url fn n" href="http://chicagoreporter.vagrant.dev/author/leeandra-khan/" title="Read All Posts By LeeAndra …
```

Add the "By" text for coauthors plus bylines

---

docs/developers/hooksfilters.rst
feed-mailchimp.php
homepages/templates/top-stories.php
inc/featured-content.php
inc/related-content.php
inc/widgets/largo-recent-posts.php

`posts_per_page` was introduced in WP 2.1, replacing/deprecating the `showposts` parameter
There was a bug where `posts_per_page` worked on WP_query but not in get_posts(), but that was fixed in WP 3.1
For more information, see:
https://codex.wordpress.org/Class_Reference/WP_Query#Pagination_Parameters
http://stackoverflow.com/a/3335128
http://core.trac.wordpress.org/ticket/15150

Update deprecated showposts parameter to posts_per_page

---

docs/developers/hooksfilters.rst
inc/ajax-functions.php

- Removes a unused argument from the reference implementation of a filter function on this filter.
Here's a live implementation of this filter: https://bitbucket.org/projectlargo/theme-chicago-reporter/src/f31772191ab00f4c6443eb9c2b57d56d0c1727ad/inc/taxonomies.php?at=master&fileviewer=file-view-default#taxonomies.php-158

Use correct arguments on example function for largo_lmp_template_partial

---

partials/content-single.php

- When checking to see if `largo_top_term()` returns anything, pass the argument ` array( 'echo' => False ) `: https://github.com/INN/Largo/blob/09367b17e4d49578dbcc22d9c0829d3668a1e3f5/inc/related-content.php#L313
- Capture the output of the checking call and echo that instead of calling `largo_top_term` a second time
Should we wrap this functionality up into a template tag, call it `largo_maybe_top_term`, and replace most uses of `largo_top_term` in templates with `largo_maybe_top_term`?

Fix top term displaying twice on single-post pages

---

homepages/templates/top-stories.php
homepages/zones/zones.php
inc/post-tags.php
partials/content-roundup.php
partials/content-series.php
partials/content-single.php
partials/content.php
partials/widget-content.php
tests/inc/test-post-tags.php

- Adds function `largo_maybe_top_term( $args )`, which outputs `largo_top_term( $args )` wrapped in an `h5.top-tag` if `largo_top_term( $args )` would return a link. If no link is returned, then it does not output the `h5.top-term`. `$args` are the same for each function.
- Adds a blank test for the function, so that we know what needs to be tested in it when we eventually write a test for it.
- to reduce the number of conditionals in templates, and to finish fixing #1316 by using #1318.
- to reduce number of database queries by halving the number of times we call `largo_top_term`

Implement largo_maybe_top_term

---

inc/featured-media.php
inc/update.php
partials/hero-featured-embed.php

In `inc/featured-media.php`'s `largo_get_featured_hero()`:
- Sets video featured media to use the `embed` type of partial, `partials/hero-featured-embed.php`: #1285 changed this to `video` but didn't create a new partial to be rendered in this space.
- Passes `$featured_media` in the `$context` variable, needed for embeds and videos, which was removed in #1285's consolidation of the largo_get_featured_`X` functions
- Passes a list of gallery IDs in the `$context` variable, needed for galleries, which was removed in #1285's consolidation of the largo_get_featured_`X` functions
In `partials/hero-featured-embed.php`, converts a short-tag `<?` to the full `<?php`
In `inc/update.php`, converts a short-tag `<?` to the full `<?php`, because now was as good a time as any to search for other `<?` …

Fix featured media display for galleries, embeds, and videos

---

inc/byline_class.php

For https://app.asana.com/0/131668199203736/193381343837860: 
- removes the 'at 12:30 PM' text from the byline of edited posts

Remove the modified date

---

inc/byline_class.php

Makes the property `$post_id` of `Largo_Byline` protected, not private, so that when `Largo_CoAuthors_Byline` extends `Largo_Byline` and uses  `Largo_Byline`'s methods `__construct` and `populate_vars`, `Largo_CoAuthors_Byline` will be able to read the variable that it tries to set.
Otherwise, anything in `Largo_CoAuthors_Byline` that uses `$this->post_id` gets a big fat `null`, and usually tries to work based off of the current post in The Loop.
This is only a bug when calling `largo_byline` with a post ID specified.

Make $post_id protected, not private

---

inc/related-content.php
tests/inc/test-related-content.php

- replace the old direct `'taxonomy'` and `'term'` query vars with a `'tax_query'` array, so we're using the modern style instead of the style deprecated in WordPress 3.1: https://codex.wordpress.org/Class_Reference/WP_Query#Taxonomy_Parameters (#1335)
- replace bad term slugs (the true cause of the issue)
- 'categories' becomes 'category'
- 'tags' becomes 'post_tag'
This probably would have been caught by https://github.com/INN/Largo/issues/884 if we had tests. 
I'll make a note of this PR on https://github.com/INN/Largo/pull/1274, which removes this widget and puts it in a plugin.

Fix Largo_Related

---

docs/users/download.rst
readme.md

- Notes minimum PHP version at https://largo.readthedocs.io/users/download.html
- Directs users to the tagged releases first, then to the master branch
- Notes minimum WordPress version in readme.md, but not in the user docs because the user docs kinda assume that you're going to be installing the latest version. The Version used here is 4.1 because that's the earliest version that the develop branch tests against at this time.
For #1344. This is a PR against master because it needs to affect largo.readthedocs.io, which only compiles from the master branch.

Document minimum PHP version for Largo

---

homepages/templates/top-stories.php

- removes a `()`
Because otherwise, any site using the "Top Stories" homepage template will have this problem:
```
Parse error: syntax error, unexpected '(' in /srv/www/citylimits/htdocs/wp-content/themes/Largo/homepages/templates/top-stories.php on line 68
```
I checked in Largo for any other cases of `' () '` in the theme's PHP files, and found these: 
```
./inc/nav-menus.php:	function largo_donate_button () {
./inc/post-metaboxes.php:function largo_layout_meta_box_display () {
./lib/options-framework/options-framework.php:function optionsframework_rolescheck () {
./lib/options-framework/options-medialibrary-uploader.php:function optionsframework_mlu_init () {
./lib/options-framework/options-medialibrary-uploader.php:function optionsframework_mlu_css () { …
```

Fix spare '()' introduced by #1319

---

inc/byline_class.php
partials/content.php

- cleans up a spare `$tags` that wasn't caught in #1280 
- defines `$output` a couple of places in the `Largo_CoAuthors_Byline` class where it might not have been defined in some cases

Define miscellaneous undefined variables

---

homepages/homepage.php

- remove an unused `get_term_by`, because we aren't using the results of that query.
For #1337

Removed unused query in homepages.php

---

partials/home-bottom-widget-area.php

- in the Homepage Bottom Widget Area homepage bottom partial, temporarily empty `$wp_query->posts`
- add comments explaining why we do this
- reference a commit and pull request that explains that a little more, because otherwise we'll be scratching our heads when we debug this the next time.
Because the first recent posts widget in homepage bottom widget area skips 10 posts when "do not duplicate" is enabled.
From Asana:
> Ben: In largo-dev/inc/widgets/largo-recent-posts.php, line 63-69, if the checkbox to ignore shown posts is checked, the widget not only ignores $shown_ids but adds the posts from the main query on the page to the list of ids to be ignored in the query. It doesn't add those posts to $shown_ids, but just joins them to the array of post ids to be ignored.
> Adam: i would …

Temporarily empty out $wp_query->posts in the homepage bottom widget area

---

inc/widgets/largo-recent-posts.php

Removed Conditional check for closing UL element on recent posts widget.  This check was causing the UL to remain open in the cases where excerpts were being displayed. 
Addresses #1330

Recent Posts Widget

---

inc/update.php
tests/inc/test-update.php

- Move `largo_remove_topstory_prominence_term` inside a <0.5 block in inc/updates.php
- Remove deprecated widget callbacks from `largo_check_deprecated_widgets` as the widgets it checks for and notifies the reader of are no longer included in Largo, and as such will be automatically removed by WordPress.
- Comment out tests for `largo_check_deprecated_widgets` so that we can still test the function without testing any callbacks.

Update functions cleanup for inc/updates.php

---

inc/update.php
lib/options-framework/options-framework.php
options.php

- Create new hook on `after_switch_theme`, the activation hook, that:
- doesn't run if there is already saved theme options for any version of Largo
- requires the default Largo options from `options.php`, which are otherwise not included in the theme outside of the options framework pages
- runs the options framework initiation function
- sets the defaults using Largo's function to do so
- sets the version number to the current version
- removes the update nag from its enqueued action, for the single page load where `after_switch_theme` runs, because at page generation time apparently the Largo version is not set in the database even though it is set during this function that appears to run before everything else on the page. (I checked with subsequent page reloads, and with some …

Show no update nag upon initial activation of Largo

---

inc/byline_class.php

These are only relevant if CoAuthors plus is enabled.
- if an author has an avatar set in CoAuthors but not in the default WordPress admin for users, this now displays the thumbnail for the user's ID instead of `null` and thereby displaying the post's thumbnail
- if an author has no Twitter set, don't display the twitter button
- if separators are hidden with CSS, still display a space between whatever-comes-before-it and the date in bylines
For #1365 and for 0.5.5 before we release that.

Fix for some bylines cases with CoAuthors

---

inc/byline_class.php

- inverts a test to see first if it's a coauthor that has an image before falling back to a different test for the author.
this fixes the behavior described in http://support.largoproject.org/helpdesk/tickets/300
> For example, on Curtis Black's latest column, a picture of Asraa is showing up in the byline of the posy. The proper image is showing up at the bottom.
The user that created the post was being shown instead of the set guest author

In Largo_Byline::avatar(), swap the test around to do the coauthors byline first

---

inc/byline_class.php

- Makes the `$author_id` property of the `Largo_Byline` class and its extenders public, because for `Largo_Byline->avatar()` to work, it needs to be able to read the `Largo_CoAuthors_Byline->author_id`, and extended classes can't read the private or protected variables of their extending classes.
This fixes the behavior documented in http://support.largoproject.org/helpdesk/tickets/300 where posts were showing author avatars based on the ID of the post's database author, not the ID of coauthors or normal wordpress users.
https://github.com/INN/Largo/pull/1374 assumed that it was just bad logic; this looked at the variables and found that one was `''` and therefore the author email address being fetched by [get_the_author_meta](https://developer.wordpress.org/reference/functions/get_the_aut …

Make the $author_id property of Largo_Byline and extending classes public

---

inc/byline_class.php

- Makes sure that bylines for guest authors have the same classes as other avatars.
On http://chicagoreporter.com/police-face-choice-of-handcuffs-or-helping-hand-for-mentally-ill/
With this fix:

Make sure that both Guest Author and WP User avatar types have the same classes

---

inc/avatars.php
inc/avatars/functions.php

On at least some post comments, a PHP error is being printed to the front end.
We're using the `get_avatar` hook, who's third parameter `$id_or_email`, is specified at `A user ID, email address, or comment object.`
We are only accommodating for a user ID or email address, and do not have code to accept a comment object.
Reference: https://codex.wordpress.org/Plugin_API/Filter_Reference/get_avatar
I've updated the offending function using the example from the codex page to also accept comment objects

Post Comment Errors

---

inc/related-content.php
inc/widgets/largo-related-posts.php

I'm not able to duplicate the bug described in https://github.com/INN/Largo/issues/1381, but this looks like a fix: exclude the current post from the posts that get returned in any query in the Largo_Related class, which is what feeds the Largo Related Posts widget.
Please wait for tests on this one.

Probable fix for https://github.com/INN/Largo/issues/1381

---

inc/update.php

Users without permissions to do theme updates are being shown messages to upgrade Largo's database. This causes confusion for these users.
Change Largo to check against `update_themes` capability

Show update notices only to users with update_themes capability

---

inc/featured-media.php

- moves a ` ` space outside some `''`

Fix comparison so that the featured media dialog displays correctly for terms

---

homepages/zones/zones.php
inc/related-content.php

- adds parameter `post__not_in` to `largo_get_recent_posts_for_term()`, an array of post IDs
- uses that parameter to exclude the homepage top story when the homepage top story is not the most-recently-published story on the site (#1384)

Add the homepage top story as a post__not_in argument on the series featured homepage layout

---

functions.php
inc/enqueue.php
lib/navis-slideshows/css/slides.css
lib/navis-slideshows/js/navis-columns.js
lib/navis-slideshows/js/navis-slideshows.js
lib/navis-slideshows/navis-slideshows.php

* Modified the media view settings to ajust the number of column options from 1-9 to 0-4. Zero (0) will create a slideshow, the others (1-4) will create a grid layout.
* Added lib/navis-slideshows/js/navis-columns.js to adjust the column numbers.
* Added `theme_gallery_defaults` filter and `gallery_zero_columns` action to functions.php.
* Moved gallery enqueques from lib/navis-slideshows/navis-slideshows.php to inc/enqueue.php to allow single images to use the lightbox functionality.
* In lib/navis-slideshows/navis-slideshows.php:
* Removed enqueues and functions referencing them.
* Changed `one-up` to `none-up` and `$columns == '1'` to `$columns == '0'` to use the new zero-column option to create the sliders.
* Changed `h6` tags to `p.wp-media-credit` or `p.permalink` to take advantage …

Gallery updates

---

inc/post-templates.php
tests/inc/test-post-templates.php

We're running a filter on post body content that checks if the post starts with an image, and if that image matches the post's featured image, removes the content from the post display (to prevent duplicate displays of that featured image).
The issue is the method we're running that check. Currently, we're getting the source for the image in the post body, then running a very slow query to lookup that image's ID in the database. This type of query/logic cannot continue to exist for performance reasons.
Every image inserted by the media editor should have a `wp-image-##` class on it, where `##` is the id of the media file. By pulling this ID out with regex, we can achieve the same effect, but avoid expensive queries.
If the html for the image has been manipulated or inserted by hand so …

Featured image performance

---

inc/related-content.php

- exclude the current post's ID from the list of ids generated by `add_from_query`, the method of the class that is responsible for generating lists of IDs in multiple parts of the `Largo_Related` class.
Something in one of the two calls to `WP_Query` in [`Largo_Related->get_series_posts()`](https://github.com/INN/Largo/blob/v0.5.5.2/inc/related-content.php#L545-L604) is ignoring the `post__not_in` argument on the query, so now I'm going to just exclude the current post's post ID from ever being added to the list of IDs
This is because of HelpScout ticket 559, and is a continuation of issue #1381 and the work done in PR #1385.

Exclude the current post from yet another area where we're creating lists of IDs

---

.travis.yml
inc/helpers.php

- Reverts changes from #1407 to the `return` portion of `largo_get_current_url()` because of #1410, but keeps the `$url` portion because it's a nice "Don't Repeat Yourself" thing.
- Adds PHP version 7.0 to Travis (does not add 7.1)
- Removes WordPress versions 4.1, 4.2, 4.3, and 4.4. 
- `return` fix because of https://github.com/INN/Largo/pull/1407#discussion_r105945697
- add 7.0 because of https://secure.php.net/supported-versions.php
- don't add 7.1 yet because we don't want to slam travis too badly
- keep PHP 5.x because WordPress still supports down to 5.2: https://wordpress.org/about/requirements/

Return support for PHP versions less than 5.5, and add 7.0 to the Travis tests.

---

functions.php

- individual `require` statements are now wrapped into one
- `require` replaced with `require_once`
- to simply the process of adding new files to be included in the future
- switch from require to require_once because we shouldn't load these files again if a child theme has loaded them for whatever reason.

Put all theme file requires into an array

---

search.php

Fixes https://github.com/INN/largo/issues/1459
I searched the repo for other cases of short tags and didn't find any:
`$ egrep -ir '<\?$' *`
Theme Check output agrees.

Remove PHP short tags

---

.travis.yml
inc/deprecated.php
inc/helpers.php
inc/post-social.php
inc/post-templates.php
lib/options-framework/options-sanitize.php
readme.md
tests/inc/test-helpers.php
tests/inc/test-post-templates.php

- Implements the matrix-based Travis CI config originally written for NPR's Story API plugin, as the research conducted [in that issue's comments](https://github.com/INN/WP-DS-NPR-API/issues/12#issuecomment-374730094) is still valid regarding which versions of PHP and PHPunit are supported by WordPress.
- We can support PHP 7.2 in tests once https://core.trac.wordpress.org/ticket/43218 is merged; this is likely to happen with WordPress 5.0
- Drops support for PHP 5.3 and 5.5, gaining support for PHP 5.6
- Gains support for PHP 5.6, 7.0, 7.1
- Removes a portion of the Travis CI config that would have messaged our Hipchat room; we stopped using Hipchat a while ago.
- Changes PHP support to whatever versions of PHP are currently receiving updates 
- Changes WordPress support to a …

Update Travis CI config, fix broken tests, update README, and diverse minor fixes

---

inc/dashboard.php

This closes #1349 in the 0.5 branch. It fixes a spacing error.
Because seeing this in the console log for every single page load makes debugging annoying:
> 2018/07/31 11:18:49 [error] 33695#0: *39 FastCGI sent in stderr: "PHP message: PHP Notice:  WP_Admin_Bar::add_node was called <strong>incorrectly</strong>. The menu ID should not be empty. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 3.3.0.) in /Users/blk/sites/largo/wp-includes/functions.php on line 4161" while reading upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/Users/blk/.valet/valet.sock:", host: "largo.test"
And because RC's commit 6e8587a141d637e01300cb0de44c6c91db5496a3 …

Copy the fix for "WP_Admin_Bar::add_node was called incorrectly" into 0.5-dev

---

lib/options-framework/options-framework.php

`screen_icon()` and `get_screen_icon()` are deprecated since WordPress 4.8.
`screen_icon()` triggers a `_deprecated_function()` call and calls `get_screen_icon()`, which outputs an HTML comment: https://developer.wordpress.org/reference/functions/get_screen_icon/
Fixes https://github.com/INN/largo/issues/1523 for https://github.com/INN/largo/issues/844

Remove screen_icon() from Options Framework options page

---

functions.php
inc/update.php
js/update-page.js

This imports the old Largo update scripts.
- Imports `inc/update.php` from Largo 0.5.53
- Imports the `of_get_option()` function so we can read from the Options Framework
- Imports the `of_set_option()` function so existing largo update functions can operate upon the Options Framework before we import those options into the new settings
- Within the `largo_perform_update()` ajax call, create a section for all optionsframework functions so that we only run those if there is an optionsframework instance in the database
- a home for #1417 functions
- this is the only place in the logic where we should `of_set_option( 'largo_version', largo_version() )` to store the post-1.0 largo version number in the Options Framework. Any other place/time would break the update logic.
- Create …

Import Largo 0.3->0.5.5.3 update functions

---

inc/term-meta.php
inc/term-sidebars.php

- adds docblocks
- adds method visibility
- sanitizes and validates some things that weren't
- adds `@todo` comments where we can do better
- cleans up code style in accordance with https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
- corrects line where we were querying for _term_meta posts by the invalid item `id` &mdash; this wasn't causing problems because the default value there is `term_id`, which was what we were querying by anyways.
- code quality
- I was in this file anyways and wanted to make sure that stuff in this file wasn't the cause of the bugs I was experiencing (https://github.com/INN/umbrella-energynewsnetwork/pull/40)

Minor improvements to code quality in inc/term-sidebars.php

---

inc/sidebars.php

Fixes an 'obviousness' deficiency in the purpose of the Homepage Bottom widget area, where it was unclear which widget area widgets should go into when using the widget area option for Theme Options > Layout > Homepage Bottom.
Because of https://secure.helpscout.net/conversation/452777097/1398/

Improve docs for the homepage-bottom widget area
