phpunit.xml
tests/bootstrap.php
tests/inc/test-avatars.php
tests/inc/test-helpers.php
tests/inc/test-taxonomies.php
tests/inc/test-users.php
tests/mock/mock-admin-functions.php
tests/mock/test-mock-admin-functions.php

This cherrypicks some tests and mocking commits from #312

Mocking functions for is_admin, more tests

---

inc/post-metaboxes.php
inc/widgets.php
inc/widgets/largo-disclaimer-widget.php
options.php
tests/widgets/test-disclaimer-widget.php

See https://github.com/INN/Largo/issues/269#issuecomment-67176905 for changes.

optional disclaimer (issue #269)

---

css/style.css
less/inc/navbar.less
partials/nav-sticky.php

See [this comment for the description](https://github.com/INN/Largo/issues/324#issuecomment-69124843) of the changes made to solve #324

Making site name visible in sticky/mobile nav on smaller viewports, for #324

---

homepages/layouts/HomepageSingle.php
homepages/layouts/HomepageSingleWithFeatured.php
homepages/layouts/HomepageSingleWithSeriesStories.php
inc/taxonomies.php
inc/update.php

Update prominence terms

---

inc/taxonomies.php
tests/inc/test-taxonomies.php

Removes the last vestiges of the Post Types and Series taxonomies for #282, I hope.

Removes optional taxonomies from quick/bulk edit views for posts

---

docs/users/contactforms.rst
lib/clean-contact/clean_contact.php

Clean contact fixes

---

inc/widgets/largo-recent-posts.php

A tiny fix to allow for easier styling.

Wrapping bylines with span.byline in Largo Recent Posts

---

inc/post-tags.php

largo_byline should pass $post_id to largo_author_link

---

homepages/zones/zones.php
inc/featured-content.php
tests/inc/test-featured-content.php

largo_get_the_main_feature now accepts a post object, stub tests

---

css/style.css
less/inc/responsive-utilities.less

Hide .hidden-desktop in viewports (min-width: 769px) and (max-width: 979px)

---

css/style.css
inc/widgets.php
inc/widgets/largo-recent-posts.php
less/inc/widgets.less

Refactor the most recent widget

---

css/editor-style.css
css/style.css
docs/conf.py
docs/developers/fordevelopers.rst
docs/developers/imagesizes.rst
docs/index.rst
docs/requirements.txt
functions.php
inc/images.php
inc/open-graph.php
inc/widgets/largo-featured.php
inc/widgets/largo-footer-featured.php
inc/widgets/largo-sidebar-featured.php
less/inc/single.less
less/inc/variables.less
less/inc/wp-responsive-media.less
partials/content-page.php
partials/content-single.php
partials/footer-sticky.php
single-one-column.php
single-two-column.php

A handful of commits for a handful of issues.

Quick fixes

---

404.php
archive.php
category.php
comments.php
feed-mailchimp.php
footer.php
full-page.php
header.php
home.php

Add PHP DocBlocks to the following 9 files:
- /404.php #472
- /archive.php #473
- /category.php #474
- /comments.php #475
- /feed-mailchimp.php #476
- /footer.php #477
- /full-page.php #478
- /header.php #480
- /home.php #481

Add PHP DocBlocks to 9 files.

---

inc/ajax-functions.php
inc/widgets/largo-author-bio.php
inc/wp-taxonomy-landing/taxonomy-landing.php
js/load-more-posts.js
partials/content-series.php
partials/footer-sticky.php
series-landing.php
tests/inc/test-ajax-functions.php

Fix for #452
This pull request also contains commits from #638, because they touch the same piece of code. That pull request can be closed once this is merged in.

Series byline fix

---

inc/ajax-functions.php

Fix for CUR-102: 'home' appearing in LMP queues.

---

inc/enqueue.php
inc/widgets/largo-facebook.php
inc/widgets/largo-follow.php
inc/widgets/largo-staff.php
inc/widgets/largo-twitter.php
less/inc/single.less

Fixes #669, #647 and #439.
The last is the trickiest to figure out how to do. I built a static variable into the widgets that use facebook/twitter scripts and conditionally check for those before including the scripts on pages that aren't single or author. There might be a better approach that I'm missing.

Assorted fixes

---

options.php

> Check this box **is** you want to show them in the header as well
> **if**

Minor typo fix

---

inc/featured-media.php

Fix for master for a condition we lost when breaking up the `single-hero.php` partial.

Respect hero override setting

---

docs/developers/hooksfilters.rst
homepages/homepage.php
homepages/zones/zones.php

Requested here: http://jira.inn.org/servicedesk/agent/HELPDESK/queues/33/HELPDESK-241

Adds a few filters to make the number of posts in homepage templates filterable.

---

inc/post-tags.php

For https://github.com/INN/Largo/issues/764

Re-add defaults for more_link and use_more in largo_excerpt

---

inc/dashboard.php

Largo Menu for WP Admin Bar

---

inc/sidebars.php
inc/wp-taxonomy-landing/functions/cftl-admin.php
options.php
partials/sidebar-fallback.php
series-landing.php

This started out as a bug fix for #642, but I spotted a bunch of stuff that was just wrong.
@aschweigert If you have a chance, it'd be great to have you confirm this patch resolves the original issue.

Various bug fixes related to sidebars on custom landing pages

---

docs/developers/index.rst
docs/developers/technicalnotes.rst
docs/feedback.rst
docs/index.rst

No more mailto: links in docs

---

homepages/templates/top-stories.php

Fix for "Homepage featured" stories stopped displaying on Top Stories homepage template.

Re-place !, spaces to tabs

---

inc/sidebars.php

Don't show footer 2 & 3 widget areas when using 1 column footer layout

---

partials/nav-global.php

Removed asterisk in file header and submitting to develop.

Inline Docs: partial nav-global to develop

---

partials/largo-header.php

Resubmitting Largo header partial and closing #908

Inline Docs: partial largo-header to develop.

---

partials/nav-secondary.php

don’t miss menu
Deleted: #904
In ref to issue: #606

Inline Docs: partial nav secondary to develop

---

partials/nav-sticky.php

sticky navigation comments and documentation

Inline docs: partial nav-sticky to develop

---

partials/nav-main.php

Add preliminary docblocks and inline comments to main navigation

Inline docs partial nav-main to develop

---

inc/enqueue.php
options.php

Identical to #910 to deploy as a hotfix.

Hotfix: FB Tracking Pixel for Master

---

docs/users/landingpages.rst

Add details on enabling series taxonomy and series landing pages, to improve clarity for users.

Landingpages.rst update on how to enable series

---

docs/users/themeoptions.rst

Add section on the new Navigation tab and how to use it's options in Appearance > Theme Options

Jack docs/users/themeoptions update

---

docs/users/taxonomies.rst

Add new section on Featured Media for Taxonomy Terms as per https://github.com/INN/Largo/issues/1016

Jack docs users taxonomies update

---

inc/avatars.php
inc/helpers.php
inc/post-tags.php
inc/users.php
inc/widgets/largo-staff.php
tests/inc/test-avatars.php
tests/inc/test-helpers.php
tests/inc/test-post-tags.php
tests/inc/test-users.php

Move some stuff around because it drives me crazy, general housekeeping.
Also removes a few profile fields (emeritus, honorary) that are practically never used and updates tests

Furniture rearrangment

---

inc/post-metaboxes.php

- adds the 'post-type' taxonomy to the terms available for the metabox
#1084 and RNS

Add post-type to the taxonomies of terms available for the Top Term

---

inc/header-footer.php
options.php

More social networks

---

partials/content.php

for http://jira.inn.org/browse/RNS-156
This should not be the full sized image (obviously). The rectangular thumb seems to work but I'd want to test this a bit and make sure that's the best size/crop to use to here

use a sane-sized image here

---

docs/developers/grunt-commands.rst
docs/developers/setup.rst

Note that gettext includes xgettext in the grunt docs

---

inc/plugin-init.php
lib/class-tgm-plugin-activation.php

update the framework, fix some text domain issues (they have a tool for that now: http://tgmpluginactivation.com/download/) and update our list of plugins

update list of plugins and tgmpa

---

docs/developers/hooksfilters.rst
inc/post-metaboxes.php

- add `largo_top_term_metabox_taxonomies` filter
- add docs
Because of #1198

Add largo_top_term_metabox_taxonomies filter to allow adding taxonomies

---

inc/featured-content.php
inc/helpers.php
inc/taxonomies.php
inc/widgets/largo-taxonomy-list.php

resubmitting #1276 as a PR against develop

rebasing this changeset to merge with develop

---

inc/update.php
inc/widgets/largo-image-widget.php

Added two @TODOs.

---

inc/post-templates.php
js/floating-social-buttons.js
js/tinymce/plugins/largo/tinymce.js
lib/lessc.inc.php

Final @TODOs added (4 total).

---

inc/widgets/largo-recent-posts.php
partials/widget-content.php

- Add toggle to Largo Recent Posts widget settings to hide the date, defaulting to false to match behavior of largo_byline().

Add option to the Largo Recent Posts widget to toggle the byline date

---

inc/featured-media.php

It's featured media, not featured image

Rename this one box

---

inc/metabox-api.php

fixes undefined error if no calls to largo_add_meta_box() are made

Metabox api fix

---

inc/enqueue.php

1. Added custom Trackers for the 3 GA accounts.
2. Updated the universal tracking code to include domain tracking for GA report segmentation.

Universal analytics

---

inc/enqueue.php

Updated array of custom tracking variables and moved the main GA function to the top of the script as recommended by GA.

update to tracking code in attempt to fix http request errors

---

inc/settings.php

This would simply address #1452.

stop php 7 warning

---

search.php

For https://github.com/INN/largo/issues/844

Fix the two remaining PHP short tags in the theme, in search.php.

---

style.css

Addresses theme check issue as part of https://github.com/INN/largo/issues/844

add a text domain to style.css
